# Generated by Django 5.2.12 on 2026-04-06 21:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conversations", "0002_message_read_archive_flags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="topic",
            field=models.CharField(
                choices=[
                    ("product", "Product Inquiry"),
                    ("order", "Order Status"),
                    ("shipping", "Delivery & Shipping"),
                    ("advice", "Brewing Advice"),
                    ("wholesale", "Wholesale & Partnership"),
                    ("other", "Other"),
                ],
                db_index=True,
                default="other",
                max_length=30,
                verbose_name="topic",
            ),
        ),
    ]
