FROM nginx:alpine

# Remove default configs
RUN rm /etc/nginx/conf.d/*

# Copy main nginx config
COPY deploy/nginx/nginx-main.conf /etc/nginx/nginx.conf

# Copy local development site config (HTTP only)
COPY deploy/nginx/site-local.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
