# Generated by Django 5.2.12 on 2026-04-06 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="If unchecked, the object will be hidden on the site.",
                        verbose_name="Active",
                    ),
                ),
                ("seo_title", models.CharField(blank=True, max_length=255, verbose_name="SEO Title")),
                ("seo_description", models.TextField(blank=True, verbose_name="SEO Description")),
                ("seo_image", models.ImageField(blank=True, null=True, upload_to="seo/", verbose_name="OG Image")),
                ("order", models.PositiveIntegerField(db_index=True, default=0, verbose_name="Sorting Order")),
                ("slug", models.SlugField(blank=True, max_length=255, unique=True, verbose_name="URL Slug")),
                ("name", models.CharField(max_length=150, verbose_name="Название")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="If unchecked, the object will be hidden on the site.",
                        verbose_name="Active",
                    ),
                ),
                ("seo_title", models.CharField(blank=True, max_length=255, verbose_name="SEO Title")),
                ("seo_description", models.TextField(blank=True, verbose_name="SEO Description")),
                ("seo_image", models.ImageField(blank=True, null=True, upload_to="seo/", verbose_name="OG Image")),
                ("order", models.PositiveIntegerField(db_index=True, default=0, verbose_name="Sorting Order")),
                ("slug", models.SlugField(blank=True, max_length=255, unique=True, verbose_name="URL Slug")),
                ("name", models.CharField(max_length=200, verbose_name="Название")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                ("price", models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Цена")),
                ("stock", models.PositiveIntegerField(default=0, verbose_name="Остаток на складе")),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="products/", verbose_name="Изображение товара"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="products.category",
                        verbose_name="Категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Товар",
                "verbose_name_plural": "Товары",
                "ordering": ["order", "name"],
            },
        ),
    ]
