# Generated by Django 5.2.12 on 2026-04-06 20:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_category_parent"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="is_featured",
            field=models.BooleanField(default=False, help_text="Show on the home page Bento grid"),
        ),
    ]
