# Generated by Django 5.2.12 on 2026-04-06 20:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_category_is_featured"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="categories/", verbose_name="Изображение"),
        ),
    ]
