# Generated by Django 5.2.12 on 2026-04-06 21:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0004_category_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="specifications",
            field=models.JSONField(blank=True, default=dict, verbose_name="Технические характеристики"),
        ),
    ]
